theme: jekyll-theme-minimal
title: Naomi T-T Levine
logo: Naomi2.jpg
description: |
  [CV](cv)
  [Organizational Relationships](organizational_relationships)
  [Research](research)
  [Methodologies](methodologies)
  [Teaching](teaching)
  [To Be Read](current_TBR_list)
  [Art](recent_artwork)
